/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lh_jni_JniKit */

#ifndef _Included_com_lh_jni_JniKit
#define _Included_com_lh_jni_JniKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lh_jni_JniKit
 * Method:    calculate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_lh_jni_JniKit_calculate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
